### PR TITLE
Better name for the "real main method"

### PR DESCRIPTION
**Pull request by phase**
Better naming conventions.

### CODE REVIEW

**Comment by bhelyer** [comment]
Thanks for the PR! 

realMain's not just init though -- it does the entire main thing. The name is a bit on the nose, isn't it? I'm drawing a blank myself though. Any thoughts?

**Comment by phase** [comment]
Why can't you just make `realMain` the `main` method? Why have a method that only calls another method?

**Comment by bhelyer** [comment]
To separate the error handling -- otherwise all the work would be in the try block, so it'd be a little harder to read.

**Comment by phase** [comment]
Do you need the error handling if you're just printing the error?

**Comment by bhelyer** [comment]
The default druntime exception handler prints out a stack trace, which obscures the message, unfortunately. Even if it could be switched off, it'd probably still print "Exception: " or something, which we don't want.

**Comment by phase** [comment]
Do 12 lines of code *really* need to be in it's own method?

**Comment by Dav1dde** [comment]
Yes. You understand exactly what the function name means when reading it, it improves readability and allows you to modify the code more easily at a later point of time.

**Pull request closed without merging**
